apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: collab-tasks
type: Opaque
stringData:
  JWT_SECRET: "supersecretjwt2024"
  MONGO_URI_AUTH: "mongodb://mongodb:27017/authdb"
  MONGO_URI_TASK: "mongodb://mongodb:27017/taskdb"

